# Generated by Django 6.0.2 on 2026-02-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
