# Generated by Django 6.0.2 on 2026-02-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
    ]
