# Generated by Django 6.0.2 on 2026-02-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='sememail@gmail.com', max_length=150),
        ),
    ]
